name: test

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ '3.0', 2.7, 2.6, 2.1, head, truffleruby-head ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        exclude:
        - { os: windows-latest, ruby: truffleruby-head }
    runs-on: ${{ matrix.os }}
    steps:
    - name: git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global advice.detachedHead 0
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install
      id: bundle
      run: |
        bundle install
        echo "exec=bundle exec" >> $GITHUB_OUTPUT
      if: "matrix.ruby <= '2.1'"
    - name: Run test
      run: ${{steps.bundle.outputs.exec}} rake test
    - id: build
      run: |
        rake build
        echo "pkg=${GITHUB_REPOSITORY#*/}-${RUNNING_OS%-*}" >> $GITHUB_OUTPUT
      env:
        RUNNING_OS: ${{matrix.os}}
      if: "matrix.ruby == '3.0'"
      shell: bash
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        path: pkg/*.gem
        name: ${{steps.build.outputs.pkg}}
      if: steps.build.outputs.pkg
